### ISSUE TITLE
No RU in the run leads to initAction failure in some cases

### ISSUE THREAD

**Issue by sethcooper** [HCALRunControl/levelOneHCALFM#124]
If there is no RU in the run, this can lead to a seg fault in some cases.
This is because the string manipulation (ruInstance.split("_")[1]) fails because the ruInstance="none" in this case.
Obviously this works in global, but I found that this happens even with the global_HCAL run key selected.
Also, normally what is in the "RUinstance" parameter isn't even the instance, but a concatenation of the application name and instance: "hcalEventBuilder_0".
Perhaps this can be handled in the same way that it is handled in global.
Alternatively, this could just cause an error (but with a better error message in the logs instead of an initAction failure), or a warning dialog message in the case where we want to warn users that they are doing something silly, but that can be overridden by expert users.

**Comment by jhakala** [comment]
I think we should do both: handle it like in global (to allow users to configure global configurations using the "global_*" run keys), otherwise go to error if no RU is there. It's not clear why this wasn't working at H2 -- global behavior should only require the correct run key and l1 roles iirc.

I don't mind calling that parameter ruInstance since I tend to think of the "0" in "hcalEventBuilder_0" as the instance number, and the FM finds the particular instances of applications it wants by using names like "hcalEventBuilder_0".

**Comment by jhakala** [comment]
I'm able to get H2 working in global mode. I think the issue was that we still had readout apps or triggering/eventbuilding apps left over by accident.
