### ISSUE TITLE
GUI support for single/Multi partition runs

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#201]
For single partition runs, user needs to check (n - 1) boxes in "mask FM" boxes from GUI, which is error-prone and not user-friendly.

John already implemented a single-partition option check-box:
![image](https://cloud.githubusercontent.com/assets/12798013/20484894/a73b4b22-aff9-11e6-8283-434da3c3b0c1.png)
After checking, a radio button allows only 1 LV-2 FM to be selected:
![image](https://cloud.githubusercontent.com/assets/12798013/20484929/c81cccf8-aff9-11e6-9ffb-723b90a1844b.png)

In #193, LV1 FM should simply count the partitions it has by the time it is going to configure, and use the correct TCDS setting.

**Comment by jhakala** [comment]
```LV1 FM should simply count the partitions it has by the time it is going to configure, and use the correct TCDS setting.```
I don't necessarily agree. It probably is more useful to have the GUI fill in a boolean parameter to specify whether single-partition TCDS settings are requested by the user, so that we could (for whatever reason) support the one-partition+LPM mode.

**Comment by sethcooper** [comment]
What happens:
- If you choose the LPM as your 1 partition?
- If you choose multiple partitions but mask the LPM?
- Same for the future localDAQ FM
- Same if we go to TCDS FMs per partition
Shouldn't these be treated specially?
Also, we have two controls here, when it seems one would do, namely, one which selects which FMs are in the run.

**Comment by jhakala** [comment]
After discussion, we decided that the radio buttons interface can handle all the cases we want, but the interface needs to be refined somewhat.

**Comment by kakwok** [comment]
Some thoughts on GUI improvement:
- "Masked FMs" should be renamed to "Multipartition" so that it is clearly the opposite of "single partition"
- "Multipartition" should be the default with the maskedFMs pre-filled. The pre-filling part will be supported by #202 . Pre-filling is important because it's not immediately clear to users that you should mask FMs in multipartition mode. Pre-filling check-boxes and displaying them as "Masked resources" would help users to figure out that.

**Comment by jhakala** [comment]
The first bullet point is done and the second is waiting on #202.

**Comment by jhakala** [comment]
So the second bullet point is done now.

I think the last GUI-related thing that may (or may not) be needed is setting a flag to indicate to the FM on the server side whether we are in singlepartition mode. I support the idea of the GUI setting a flag in the form of a parameter (perhaps a BoolT called "SINGLEPARTITION_MODE") for the server to check, as opposed to any server-side logic of counting partitions (especially since that would make it nontrivial to support a 1-partition+LPM use case.)

If this sounds okay I will make the SINGLEPARTITION_MODE bool and set it in the gui corresponding to whether the user selects the "singlepartition" or "multipartition" panel (which has replaced the above screenshot in the radioButtons branch). 

The only remaining complication left is whether to allow a user to mask the TCDSLPM FM while in multipartition mode. I actually have done this before for a test, so I think we can allow the user to make that choice (even though it's a corner case).

**Comment by jhakala** [comment]
Successfully tested after #230. Further refinements can go in new issues.
