### ISSUE TITLE
Move TCDS handling to FM

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#204]
Seth made the conversion of TCDS app to a service app on the fly.
We should make a QRcontainer for ici and PI, then configure them with the ControlSequences from Mastersnippet.

**Comment by jhakala** [comment]
This new functionality will be important for the implementation of the new localDAQFM configuration scheme.

**Comment by sethcooper** [comment]
Technically we can do the localDAQFM without this. It would just mean telling the supervisor connected to the iCI/LPM applications to configure them only, and not start or stop them. (That is what happens now when the supervisor is in the same executive as the trigger adapter.) Rather than implement that, I think we should use this opportunity to get rid of the "two bosses" TCDS scheme. Plus it would make the LPM FM more sensible.

**Comment by jhakala** [comment]
Can we recap what the result of this campaign was? We had this PR, which got closed without a merge, with no explanation of the results:
#214

I am wondering what the status was because I think moving TCDS handling to the FM may be a good solution for the issue of configuring the LPM out of proper order.

**Comment by jhakala** [comment]
For the record, Martin gave this recap of the status of the FM handling TCDS:
```
The conclusion from the tests I’ve done with Seth was that, handling TCDS on FM side will not be as neat as we had dreamed of.
Main reason being TriggerAdapter has to talk to ici/LPM to start the local runs.

So it’s difficult to divide the work between FM and TA. 
FM intrinsically is difficult to schedule tasks among applications across partitions, which in this case is essential, because we need to order the start sequence between TA and LPM, which are under different FMs.

while that’s an easy task for supervisor, as long as it has the connections for the apps.
```

**Comment by jhakala** [comment]
Should this be closed? It seems we have given up on the FM handling TCDS, so we could close all the issues we have related to that unless there is still a drive for it.

**Comment by kakwok** [comment]
Yes. With RCMS 4.6.4, the TCDS applications in our configuration have been converted into virtual resources in order to maintain the ability of masking and running configurations in parallel. Therefore, FM no longer "see" TCDS applications.
