### ISSUE TITLE
Add new runkey attribute to help picking single partition FM

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#234]
Runkeys should have an optional attribute called `defaultPartition`, which will be used by GUI to pre-click the desired partition in the single partition mode.
The corresponding FM parameter should be `DEFAULT_PARTITION`

**Comment by jhakala** [comment]
We probably want this as a part of the AVAILABLE_RUN_CONFIGS, unless we want it to apply to every run key in a partition. I think associating it with individual run keys is more flexible overall, since one could envision a future where certain singlepartition runs are part of health checks, and needing multiple configurations and grandmasters for those would be cumbersome.

**Comment by kakwok** [comment]
Done in 0531c8480437d2a15c542f31104ceb47251737ed
