### ISSUE TITLE
minimalist control box

### ISSUE THREAD

**Issue by elaird** [HCALRunControl/levelOneHCALFM#250]
What would you think of removing some non-essential text and buttons from the control box?
Current:
![current](https://cloud.githubusercontent.com/assets/994467/23274716/05651314-fa04-11e6-845c-939e2f34be41.png)

Mockup:
![mockup](https://cloud.githubusercontent.com/assets/994467/23274720/093ac876-fa04-11e6-895a-baea9bc24745.png)

**Comment by jhakala** [comment]
My thoughts: first, this seems that it makes experts' lives easier but might make life tougher for e.g. inexperienced DOCs. For example, it might not be obvious to an untrained eye what exactly is the configuration name from the example you showed. For hiding and showing buttons, at least us FM devs sometimes want to use buttons like "Reset," so probably it would be best to just move them to some "expert view" as opposed to removing them. 

More technically -- the buttons (and indeed the entire control box) we have now are actually rendered by framework code (see e.g. [1]), and the extent to which the HCALFM gui modifies the buttons+control box is limited to moving and restyling the state name, and some trickery for moving and renaming Halt+Destroy and hiding a button for one broken transition (paused to halt iirc). It's all ad-hoc in the current scheme, so it's hard for me to imagine a systematic way of coding it up in the gui without a lot of overhead putting in logic for every button. One could in principle replace the button renderer with something custom, or maybe easier would be to beef up our custom HCALParameterSender (which only sends our realtime updating parameters right now) so that the server's built-in wisdom about e.g. what commands are allowed from the current state could be sent to the GUI ansynchronously in the form of a parameter. That would be a nontrivial project, so I don't see it happening very quickly.

[1] /RCMS/framework/gui/src/rcms/gui/tag/control/ButtonsJSRenderer.java

**Comment by jhakala** [comment]
Since @elaird hasn't responded with input/ideas, I think we can table this for now with a (non-binding) "won't do".
