### ISSUE TITLE
Color changes to reflect FM masking/selection

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#255]
Ted suggested to me that in multipartition mode, we can make all unmasked FM coloured in green and on checking a box, the colour of the FM will turn red. The logic should revert in singlepartition mode.

I think this will help reducing user errors and better reflect the inversion of logic between multipartition and singlepartition mode.

**Comment by jhakala** [comment]
Instead of the color of the FM name, what do we think about restyling the checkboxes and radiobuttons so that they have a color? Colored text is a bit ugly in most situations and can result in readability issues.

One might be able to do this without touching the html or js -- only the css -- according to the nice recipes here:
https://kyusuf.com/post/completely-css-custom-checkbox-radio-buttons-and-select-boxes

**Comment by jhakala** [comment]
Done in  bd50295:
<img width="668" alt="image" src="https://cloud.githubusercontent.com/assets/8178838/23681569/11daab90-0355-11e7-905a-d2d5bc66b22d.png">
<img width="684" alt="image" src="https://cloud.githubusercontent.com/assets/8178838/23681578/1a684f56-0355-11e7-8ba1-301977867b27.png">

**Comment by jhakala** [comment]
We should check how this looks at p5 because the spacing might be a little weird.

**Comment by sethcooper** [comment]
It's not possible to also keep the check in the checkbox or the black marker in the radio buttons?

**Comment by jhakala** [comment]
It is possible, but I asked Martin and he said he prefers just color. Plus, adding checks back to the multipartition panel brings us back to the question: does a check mean it's masked, or in? Anyhow, if there are other opinions, I could add the checks/dots back or even use some sort of icons: e.g. ✅ vs ❌
