### ISSUE TITLE
SID = 0 in conjunction with oracle error

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#259]
We had a problem with the LogSessionConnector that seemed to stem from an oracle DB error telling us that we had too many open cursors. It is possible that this is due to a bug in the HCALFM, especially considering that the problem went away once the cmsrc-hcal tomcat was restarted (of course real diagnostics and an actual fix would be better). See the below image for the error message and symptom.

![image](https://cloud.githubusercontent.com/assets/8178838/23835643/f913feda-0738-11e7-8b60-1036e4f7478a.png)

**Comment by kakwok** [comment]
That weekend was particular bad not due to FM but rather DQM have excessive connections made to RUNINFO server, as reported by the oracle DB support. Here is the count of connections made over 5 hrs by oracle support team. So it's not really our problem.
```
CMS_HCL_RUNINFO                         
OS_USERNAME                     COUNT(*)
------------------------- --------------
hcalpro                              400 -  
hcaldqm                            53070  -
```
What's interesting is that 1) we still opened 400 connections 2) we still have SID=0 after tomcat restart.
For 1), I opened #258 because I suspect we could be opening unnecessary connections to RunInfo DB.
For 2), I checked the logs of those runs and found we obtained and closed a non-zero SID for them and also those were the runs that went into ERROR at some point. So I suspect the SID is just not getting published. I am testing if publishing on starting, which is as soon as we have the run number, would fix this problem.

**Comment by jhakala** [comment]
Okay, so maybe this can be closed. But perhaps we should request that the DQM use a different username for accessing the runinfo DB? It doesn't seem safe to me to be in a situation where the DQM can mess up the FM (and vice-versa).

Also, it would be useful to add this diagnostic info you've posted here to #258.

**Comment by kakwok** [comment]
Have not seen SID=0 after publishing on starting.
