### ISSUE TITLE
automate some clicks

### ISSUE THREAD

**Issue by elaird** [HCALRunControl/levelOneHCALFM#268]
The most common workflow is to click "Set parameters", then "Initialize", then "Configure".  Might it be of interest to make a button "Set & Init & Configure" to do all three in sequence via one click?

**Comment by jhakala** [comment]
This sounds desirable and doable, but unless #265 gets merged, it would be very buggy. Currently #265 is in limbo because there are concerns over whether users would like it, but from my side, I would like to see it merged soon. Then we can start introducing more automation like what's requested here.

**Comment by jhakala** [comment]
Done in  27b9fc9. Due to a git mistake, I'll submit the PR after #313 is merged.
