### ISSUE TITLE
Standalone review

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#271]
There is a reminder from Marc in the DAQ user forum [1,slide6] that software should be able to run standalone on P5 network, i.e. does not require connections to the outside world.

We should make sure we satisfy this requirement.

[1] https://indico.cern.ch/event/626558/contributions/2530230/attachments/1440454/2217363/SysAdmin_CMSWeek_170405.pdf

**Comment by jhakala** [comment]
I'm pretty sure we're good to go. For one, P5 is by nature cut off from the outside internet. We don't rely on a connection to lxplus for anything besides the non-essential webHandsawBot. We do look for a google font, but I show below what it looks like with and without that font respectively:

with:
![screenshot-5](https://cloud.githubusercontent.com/assets/8178838/24818887/e276e95c-1ba7-11e7-82f2-38e532e40768.png)
without:
![screenshot-4](https://cloud.githubusercontent.com/assets/8178838/24818846/c1b07f9e-1ba7-11e7-9dfb-f0548671f06f.png)

Aside from that I think we're good. We have one line that I'm not sure what it does in the server side code:
https://github.com/HCALRunControl/levelOneHCALFM/blame/master/src/rcms/fm/app/level1/HCALEventHandler.java#L942
which I think has been there forever, but I don't think it does any harm (since it wouldn't work already if it used the www to try to reach that url).

Below I show a grep of where we might be trying to access the www, and it is mostly just comments.
```https://github.com/HCALRunControl/levelOneHCALFM/blame/master/src/rcms/fm/app/level1/HCALEventHandler.java#L942```
