### ISSUE TITLE
Clear error message on GUI upon reset

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#283]
Both LV1 and LV2 FM's `SUPERVISOR_ERROR` are set to `""` during resetAction, and the parameterSender sends notification xml to GUI, however the parameter value does not propagate to GUI successfully.

**Comment by jhakala** [comment]
Done in #308. Two things were going on here:

1) Something in the framework's AJAX handling (drawMyCommandButtons ?) was not doing the GUI updating when it received an AJAX notification of a parameter whose value was empty. This might be for a good reason: our other guiParams get handled the same way so changing how it handles null values of parameters might cause problems with our otherwise working realtime-updating parameters. So I just changed the default value of the SUPERVISOR_ERROR to "not set".

2) I added something to showSupervisorError such that when the supervisor error changes to "not set", it overwrites the supervisor_error in the gui and hides its div. Previously it would not do anything asynchronously to hide the message.
