### ISSUE TITLE
different colors for different sections of error messages

### ISSUE THREAD

**Issue by elaird** [HCALRunControl/levelOneHCALFM#374]
When a configuration transitions to error, the resulting message on the GUI is often the length of a paragraph.  Could the structurally different sections of the message appear in different colors?  This would help a user to decode the message.

**Comment by jhakala** [comment]
Could you give an example of what you would like to see? I'm not sure I understand what you have in mind.

**Comment by elaird** [comment]
e.g., on page 25 of https://indico.cern.ch/event/710455/contributions/2941947/attachments/1620215/2577367/HCALFM_forDOC.pdf , the timetatmp up to "_HBHEc]" could be yellow, the "(hcal::uHTRManager:8)" (and 7 and 6) could be orange, and the exception could be red.

**Comment by sethcooper** [comment]
Perhaps it would be helpful to display a list of applications and the associated error messages.  The hcalSupervisor can publish a list of application names/instances/error messages instead of just one long appended string as it does now.  Then the FM can format them into a nicer display, perhaps row by row or something.

**Comment by jhakala** [comment]
I am trying to think how the FM could endow fancier styling on the error message, and I think Seth's suggestion is probably on the right track -- I think we'd probably want a new parameter in the HCALFM's server side, since:

-  the error message that appears in the GUI now is just a string passed to the GUI from the server side, and it wouldn't make sense to try to put error message parsing logic into the GUI (since our error messages come in all shapes and sizes; they're not consistently formatted)
- the error message that the server side passes to the GUI probably shouldn't embed HTML styling into the error message, since then that HTML styling would also go into the LogCollector logs [and e.g. if there were tags like <span style="color: orange"> inserted into the error messages in the server side, then the message would not mix nicely with the xml format of the LogCollector logs; later Handsaw.pl converts that to ascii for displaying on a terminal, and  webHandsaw converts the ascii back to html, so handling the formatting tags would be a nightmare]
- therefore I suggest a new parameter along the lines of what Seth is saying. This parameter could maybe be a VectorT<MapT<StringT>> with the format 
```
[  {  "timestamp" : "13:37:59 CEDT", 
      "app" : "hcalUHTRmanager_01", 
      "message":"I ZS'd myself and have no TPs!"
    } ,
   {"timestamp" : ....
   }
]
Then if we have a parameter that is structured like that, the GUI could format it nicely without difficult parsing or fancy logic.

**Comment by sethcooper** [comment]
We can’t pass a MapT from xdaq, so I suggest 3 vectors of app name, instance, and message. The timestamp can be added by the FM as is now.

**Comment by jhakala** [comment]
Sure, xdaq can have three vectors, and I think the FM could still have a `VectorT<MapT<StringT>>`; we just get the vectors from xdaq and piece them together into the FM's `VectorT<MapT<StringT>>` (in other words, the FM doesn't need to have three different vectors as global parameters to mirror xdaq; we can just get the vectors from xdaq, not save them as global parameters, but piece them together into the one parameter instead).

**Comment by kakwok** [comment]
@jhakala 
I put the error from supervisor in your desired format in the parameter `XDAQ_ERR_MSG`, which is available in LV1's parameter:
https://github.com/HCALRunControl/levelOneHCALFM/tree/errMsgFormat

I may need to iron out some cases when we don't get error from supervisor,
but you can start to think of a nice way to format the errorMessage in the GUI.
The information available would be something like this:
```
     ERROR [HCAL HCALFM_LVL1_904Int] :XDAQ_ERR_MSG from LV2=HCAL_HO904 value=[{hcalCrate:6=init Caught exception: hcal::exception::Exception 'Could not connect to crate 0 on bus caenpcie:0 . Could not connect to VME controller board' raised at init(/builds/cmshcos/hcal/hcalAux/src/common/hcalCrate.cc:180)}]
```

**Comment by jhakala** [comment]
This is done in #391; that PR needs a little more work to sort out #389 and then needs to be tested, but I'll close this now.

**Comment by kakwok** [comment]
I like the table, but i think having timestamp on each row is redundant. Perhaps we should just give a header to the table via SUPERVISOR_ERROR with something like: `[timestamp] Supervisor reports the following errors:`

**Comment by jhakala** [comment]
Hmm, the timestamp could be suppressed, but it might be useful in the case where multiple supervisors have issues (perhaps at different times during their lifecycles), especially if one is looking at the LogCollector logs to find details.

**Comment by kakwok** [comment]
The timestamp would not be exactly corresponding to the `logger.error` in the log anyway. That's also why I think a single timestamp in the header will be less confusing and saves more space for App name and errMessage.
LV1 collects all LV2's error message and put that in the single map, that's why in the app name I added the partition name.
