### ISSUE TITLE
Speed up Starting

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#83]
HCAL is the slowest subsystem on Starting. We should figure out how to shave off a few seconds. It is suspected that this slowness is due to the poll/sleep loop we do instead of using notifications between the level2's to the level1.

**Comment by sethcooper** [comment]
There are some related points:
1) We currently don't use async soap communication with the supervisor at all for some reason
2) The supervisor should be enabled with async enable (so that it immediately updates its state vector)
3) The supervisor commands should all be of the "async" variety (for the same reason)

However, I'm not sure that any of those will fix the slow starting.
It may be that enabling the RBXs takes up extra time.
A detailed accounting of where the time goes, including the enable time for the supervisors, should be done at P5.

**Comment by kakwok** [comment]
For (2), it looks like we have not enabled it in the userXML from here:
https://github.com/HCALRunControl/levelOneHCALFM/blob/master/src/rcms/fm/app/level1/HCALEventHandler.java#L353

**Comment by jhakala** [comment]
Notes on studies done on this would be appreciated.

**Comment by kakwok** [comment]
Before the test the starting phrase in miniDAQ takes:
  HCAL: ~4.5s
  HF  : ~1s
These values were consistent with a few global runs taken before the test was performed.

Updated FM which default to use AsyncSOAP.
Updated HCAL+ HF miniDAQ configuration:
  -Added 'ReportStateToRCMS' to all supervisors
  -Added 'HCALSupervisorAsyncEnable' to LV1 and LV2 FM's userXML

Checked all infospaces to confirm ReportStateToRCMS=true.

1)When 'HCALSupervisorAsyncEnable' only applied to LV2's userXML:
HCAL takes ~4.5s, HF takes ~4s
2)When 'HCALSupervisorAsyncEnable' applied to both LV1 and LV2's userXML:
HCAL takes ~8s, HF takes ~4s

Need to explain:
1) Why using async correctly bring HF from 1s to 4s? Do we observe this in H2?
2) Why putting AsyncEnable in LV1 userXML would make a big difference

**Comment by jhakala** [comment]
I see two starts out of the last six have start times 11.8 sec and 16.5 sec. The rest are around 4 seconds. The behavior is inconsistent and 16.5 puts us squarely as the slowest and delays datataking.

**Comment by jhakala** [comment]
Hopefully fixed by Andrea/Jeremy
